version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - output:/usr/src/app/output
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "80:80"

volumes:
  output:
